name: Borsa Botu

on:
  schedule:
    - cron: '30 16 * * 1-5' # TSİ 19:30
  workflow_dispatch: # Manuel çalıştırma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari cek
        uses: actions/checkout@v2

      - name: Python kur
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Kutuphaneleri yukle
        run: |
          pip install pandas tradingview_ta python-telegram-bot alpaca-trade-api

      - name: 1. Adim - Analiz Raporunu Gonder
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python otomatik_emir.py

            - name: 2. Adim - Otomatik Al-Sat Yap
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python otomatik_emir.py

